version: "3.8"

services:
  db:
    image: mongo:8.0.9-noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadminsolid
      MONGO_INITDB_ROOT_PASSWORD: mongopasswordsolid
    volumes:
      - mongo-data:/data/db
  app:
    build: ./
    restart: always
    ports:
      - "8081:8080"
    environment:
      - REDIRECT_URI=http://localhost:8080/login/oauth2/code/linkedin
      - CLIENT_ID=772w40zxnlt72c
      - CLIENT_SECRET=CLIENT_SECRET=WPL_AP1.H8G4gVgkc7umC1k9.mAHopA==
      - DB_URL=mongodb://mongoadminsolid:mongopasswordsolid@db:27017/solid?authSource=admin
volumes:
  mongo-data:
