version: "3.8"

services:
  db:
    image: mongo:8.0.9-noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadminsolid
      MONGO_INITDB_ROOT_PASSWORD: mongopasswordsolid
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
