spring:
  application:
    name: app.solid
  data:
    mongodb:
      uri: mongodb://mongoadminsolid:mongopasswordsolid@localhost:27017/solid?authSource=admin
  security:
    oauth2:
      client:
        registration:
          linkedin:
            client-id: ${LINKEDIN_CLIENT_ID}
            client-secret: ${LINKEDIN_SECRET_ID}
            scope: openid, profile, email, w_member_social
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: LinkedIn
            authorization-grant-type: authorization_code
            provider: linkedin
            client_authentication_method: client_secret_post

        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/userinfo
#            user-info-uri: https://api.linkedin.com/v2/me,
#            user-name-attribute: id
            jwk-set-uri: https://www.linkedin.com/oauth/openid/jwks